version: '3.3'
services:
  alarmservice:
    #image: docker.io/logops/alarm-service:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alarmservice
    environment:
      - MONGO_HOST = "mongodb://mongo:27018"
    ports:
      - 8085:8085
    depends_on:
      - mongo
    networks:
      - alarmservice

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    networks:
      - alarmservice
    volumes:
      - "mongoalarm:/data/db"

networks:
  alarmservice:

volumes:
  mongoalarm:
