apiVersion: v1
kind: Service
metadata:
  name: alarm-service
spec:
  selector:
    app: alarm-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-app-deployment
  labels:
    app: alarm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarm-app
  template:
    metadata:
      labels:
        app: alarm-app
    spec:
      containers:
      - name: alarm-app
        image: logops/alarm-service:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        env:
        - name: MONGO_HOST
          value: alarm-db-service
        - name: MONGO_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: alarm-db-service
spec:
  selector:
    app: alarm-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-db-deployment
  labels:
    app: alarm-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarm-db
  template:
    metadata:
      labels:
        app: alarm-db
    spec:
      containers:
      - name: alarm-db
        image: mongo
        ports:
        - containerPort: 27017
