---
micronaut:
  application:
    name: log-alarm-service
  server:
    port: 8085

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27018}"
  #datastoreImpl: Hibernate
#grails:
#  mongodb:
#    databaseName:
---
jackson:
  date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
  serialization-inclusion: "always"

---
datasources.default: {}
---
#hibernate:
#  hbm2ddl:
#    auto: update
  #cache:
    # queries: false
    # use_second_level_cache: true
    # use_query_cache: false
    # region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
dataSource:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''
